import type { Metadata } from "next";
import { Geist, Geist_Mono, Instrument_Sans, Instrument_Serif, Inter } from "next/font/google";
import "./globals.css";
import { GeistPixelCircle } from "geist/font/pixel";
import { Analytics } from "@vercel/analytics/next"
import LenisProvider from "../components/LenisProvider";
import { cn } from "@/lib/utils";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const instrumentSans = Instrument_Sans({
  subsets: ["latin"],
  variable: "--font-instrument-sans",
  display: "swap",
});

const instrumentSerif = Instrument_Serif({
  variable: "--font-instrument-serif",
  subsets: ["latin"],
  weight: "400",
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Builder House'26 - ft. TokenSupply",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, GeistPixelCircle.variable, instrumentSerif.variable, instrumentSans.variable, "font-sans", inter.variable)}
    >

      <body className="min-h-full flex flex-col bg-zinc-950 text-white">
        <LenisProvider>{children}</LenisProvider>
        <Analytics/>
      </body>
    </html>
  );
}
